Repo_Pattern_MVC/Models/jsonMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Repo_Pattern_MVC.Utility
{
	public class jsonMessage
	{
		public string Message { get; set; }
		public bool Status { get; set; }

	}
}

Repo_Pattern_MVC/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Repo_Pattern_MVC.Areas.Admin.Controllers
{
    public class AdminHomeController : Controller
    {
        // GET: Admin/AdminHome
        public ActionResult Index()
        {
            return View();
        }
    }
}

Repo_Pattern_MVC/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Repo_Pattern_MVC.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Admin/Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

Repo_Pattern_MVC/Areas/Admin/Controllers/FormBuilderController.cs
using Repo_Pattern_MVC.Utility;
using Repo_Pattern_MVC_Model;
using Repo_Pattern_MVC_Model.Model;
using Repo_pattern_MVC_Repository.Service;
using Repo_pattern_MVC_Repository.ServiceContract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Repo_Pattern_MVC.Areas.Admin.Controllers
{
	public class FormBuilderController : Controller
	{
		// GET: Admin/FormBuilder
		IHome_Repository _Home_Repository = new Home_Repository(new Repo_Pattern_MVCEntities());

		public ActionResult Index()
		{
			return View();
		}
		public ActionResult FormList()
		{
			return View();
		}
		[ValidateInput(false)]
		public JsonResult SaveDyanamicForm(string FormName, string Form_Json, string Form_HTML)
		{
			var result = new jsonMessage();
			try
			{
				Form_Master _modal = new Form_Master();
				_modal.Form_Name = FormName;
				_modal.Form_Body_Json = Form_Json;
				_modal.Form_Body_Html = Form_HTML;

				int Issave = _Home_Repository.SaveDynamicForm(_modal);
				if (Issave == 1)
				{
					result.Message = "Form has beed saved successfully.";
					result.Status = true;
				}

			}
			catch (Exception ex)
			{
				//ErrorLogers.ErrorLog(ex);
				result.Message = ex.ToString();
				result.Status = false;
			}
			return Json(result, JsonRequestBehavior.AllowGet);
		}

		public JsonResult GetDyanamicForm(string id)
		{

			return Json(new { data = _Home_Repository.GetFormNamebyID(Convert.ToInt32(id)) }, JsonRequestBehavior.AllowGet);
		}
		public JsonResult GetDyanamicSubmitedFormById(string id)
		{

			return Json(new { data = _Home_Repository.GetSubmitedFormDatabyID(Convert.ToInt32(id)) }, JsonRequestBehavior.AllowGet);
		}
		public JsonResult GetFormList()
		{
			List<Form_Data_Master> _list = new List<Form_Data_Master>();

			try
			{
				_list = _Home_Repository.GetFormList();
				var result = from c in _list
										 select new[]
										 {
													Convert.ToString( c.Id ),  // 0     
                          Convert.ToString( c.UserId ),  // 1     
                          Convert.ToString( c.UserName ),
													 c.Form_Data ,// 2     
                          "",  // 3     
                                                   };

				return Json(new
				{
					aaData = result
				}, JsonRequestBehavior.AllowGet);
			}

			catch (Exception ex)
			{
				
				return Json(new
				{
					aaData = new List<string[]> { }
				}, JsonRequestBehavior.AllowGet);
			}
			;
		}
		public bool CheckFormnameExist(string FormName)
		{
			var returnval=_Home_Repository.CheckFormnameExist(FormName);
			return returnval;
		}
	}
	}

Repo_Pattern_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repo_Pattern_MVC.Utility;
using Repo_Pattern_MVC_Model;
using Repo_Pattern_MVC_Model.Model;
using Repo_pattern_MVC_Repository.Service;
using Repo_pattern_MVC_Repository.ServiceContract;

namespace Repo_Pattern_MVC.Controllers
{
	public class HomeController : Controller
	{
		IHome_Repository _Home_Repository = new Home_Repository(new Repo_Pattern_MVCEntities());
		public ActionResult Index()
		{
		ViewBag.FormnameList=	_Home_Repository.GetFormName();
			return View();
		}
		
		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
		[ValidateInput(false)]
		public JsonResult SaveForm(int UserId, string UserName, string Form_Data)
		{
			var result = new jsonMessage();
			try
			{
				Form_Data_Master _modal = new Form_Data_Master();
				_modal.UserId = UserId;
				_modal.UserName = UserName;
				_modal.Form_Data = Form_Data;

				int Issave = _Home_Repository.SaveForm(_modal);
				if (Issave == 1)
				{
					result.Message = "Form has beed submited successfully.";
					result.Status = true;
				}

			}
			catch (Exception ex)
			{
				//ErrorLogers.ErrorLog(ex);
				result.Message = ex.ToString();
				result.Status = false;
			}
			return Json(result, JsonRequestBehavior.AllowGet);
		}

	}
}

Repo_Pattern_MVC/Areas/Admin/Views/AdminHome/Index.cshtml
@{
	ViewBag.Title = "Index";

}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>AdminLTE 2 | Log in</title>
	<!-- Tell the browser to be responsive to screen width -->
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<!-- Bootstrap 3.3.7 -->
	
	<link rel="stylesheet" href="~/Areas/Admin/Content/bower_components/bootstrap/dist/css/bootstrap.min.css">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="~/Areas/Admin/Content/bower_components/font-awesome/css/font-awesome.min.css">
	<!-- Ionicons -->
	<link rel="stylesheet" href="~/Areas/Admin/Content/bower_components/Ionicons/css/ionicons.min.css">
	<!-- Theme style -->
	<link rel="stylesheet" href="~/Areas/Admin/Content/dist/css/AdminLTE.min.css">
	<!-- iCheck -->
	<link rel="stylesheet" href="~/Areas/Admin/Content/plugins/iCheck/square/blue.css">
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	<!-- Google Font -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
	<div class="login-box">
		<div class="login-logo">
			<a href="#"><b>Login</b>DEMO</a>
		</div>
		<!-- /.login-logo -->
		<div class="login-box-body">
			<p class="login-box-msg">Sign in to start your session</p>
			<form action="@Url.Action("Index","FormBuilder")" method="post">
				<div class="form-group has-feedback">
					<input type="email" class="form-control" placeholder="Email">
					<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
				</div>
				<div class="form-group has-feedback">
					<input type="password" class="form-control" placeholder="Password">
					<span class="glyphicon glyphicon-lock form-control-feedback"></span>
				</div>
				<div class="row">
					<div class="col-xs-8">
						<div class="checkbox icheck">
							<label>
								<input type="checkbox"> Remember Me
							</label>
						</div>
					</div>
					<!-- /.col -->
					<div class="col-xs-4">
						<button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
					</div>
					<!-- /.col -->
				</div>
			</form>
			<div class="social-auth-links text-center">
				<p>- OR -</p>
				<a href="#" class="btn btn-block btn-social btn-facebook btn-flat">
					<i class="fa fa-facebook"></i> Sign in using
					Facebook
				</a>
				<a href="#" class="btn btn-block btn-social btn-google btn-flat">
					<i class="fa fa-google-plus"></i> Sign in using
					Google+
				</a>
			</div>
			<!-- /.social-auth-links -->
			<a href="#">I forgot my password</a><br>
			<a href="register.html" class="text-center">Register a new membership</a>
		</div>
		<!-- /.login-box-body -->
	</div>
	<!-- /.login-box -->
	<!-- jQuery 3 -->
	<script src="~/Areas/Admin/Content/bower_components/jquery/dist/jquery.min.js"></script>
	<!-- Bootstrap 3.3.7 -->
	<script src="~/Areas/Admin/Content/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
	<!-- iCheck -->
	<script src="~/Areas/Admin/Content/plugins/iCheck/icheck.min.js"></script>
	<script>$(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });</script>
</body>
</html>

Repo_Pattern_MVC/Areas/Admin/Views/FormBuilder/FormList.cshtml
@{
	ViewBag.Title = "FormList";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

}
<!-- jQuery 3 -->
<script src="~/Areas/Admin/Content/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>
			Servay form list
			<small>user wise servay form list</small>
		</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
			<li class="active">Servay list</li>
		</ol>
	</section>

	<!-- Main content -->
	<section class="content">
		<div class="row">
			<div class="col-xs-12">
				<div class="box">
					<div class="box-header">
						<h3 class="box-title">Servay Form List</h3>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						<table id="tblFormlist" class="table table-bordered table-hover">
							<thead>
								<tr>
									<th>Id</th>
									<th>Userr Id</th>
									<th>User Name</th>
									<th>Form Data</th>


								</tr>
							</thead>
							<tbody></tbody>

						</table>
					</div>
					<!-- /.box-body -->
				</div>
				<!-- /.box -->
			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
	</section>
	<!-- /.content -->
</div>
<!-- /.content-wrapper -->
<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
	<div class="modal-dialog">

		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title"></h4>
			</div>
			<div class="modal-body">
			<div id="showmodaldata"></div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>

	</div>
</div>

<script>
	$(document).ready(function () {
		windowResize();
		
	});
	$(window).resize(function () {
		windowResize();
	});
		function windowResize() {
			display();

		};
	function display() {
		var Table = $('#tblFormlist').DataTable({

               "processing": true,
               "serverSide": false,
               "paging": true,
               "ordering": true,
               "info": true,
               "searching": true,
               "bFilter": false,
               "scrollX": "100%",
               "scrollY": ($(window).height() - 500),
               "sScrollXInner": "100%",
               "bScrollCollapse": true,
               "sAjaxSource": '@Url.Action("GetFormList", "FormBuilder")',
               "bDestroy": true,
               "bLengthChange": true,
               "bPaginate": true,
               "sEmptyTable": "Loading data from server",

               "columns": [

                   {
                       "sWidth": "5%",
                       "sClass": "TextCenter Id",
                       "render": function (data, type, row) {
                           return row[0];
                       }
                   },
                   { "sWidth": "5%", "sClass": "TextCenter Name", "render": function (data, type, row ) { return (row[1]); } },
                   { "sWidth": "5%", "sClass": "TextCenter Desc", "render": function (data, type, row ) { return (row[2]); } },

                    {
                        "bSortable": false,
                        "sClass": "TextCenter",
                        "sWidth": "3%",
											"render": function (data, type, row) {
												return '<center><a href="javascript:void(0);" onclick="showdata(' + row[0] + ');" > <i class="fa fa-list-alt" aria-hidden="true"></i></a> </center>';
                        }, "targets": 0,
                    }

               ],

           });

	};
	function showdata(id) {
		
		$.ajax({
			url: "/FormBuilder/GetDyanamicSubmitedFormById",
			type: "POST",
			data: { id: id },
			dataType: "json",
			success: function (data) {
				
				$("#showmodaldata").html(data.data[0].Form_Data);
				$(".modal-title").text("this form submited by "+data.data[0].UserName);
				$("#LoadDynamicForm").css("display", "block");
				$('#myModal').modal('show');
			},
			error: function (a, b, c) {
				toastr.error(c);
			}
		});
	
	}
</script>

Repo_Pattern_MVC/Areas/Admin/Views/FormBuilder/Index.cshtml
@{
	ViewBag.Title = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

}

<link href="~/Areas/Admin/Content/formbuilder/css/demo.css" rel="stylesheet" />

<link href="~/Areas/Admin/Content/formbuilder/css/jquery.rateyo.min.css" rel="stylesheet" />

<title>Dynamic FormBuilder Demo</title>
<style>

	.form-active {
		padding: 10px !important;
		border-radius: 10px !important;
		background-color: #fff !important;
	}

	.copy-html {
		color: #fff;
		background-color: #1b3249;
		border-color: transparent;
		display: none;
	}

	.edit-form {
		color: #fff;
		background-color: #69727c;
		border-color: transparent;
		float: left !important;
	}

		.edit-form:hover {
			color: #fff;
			background-color: #69727c;
			border-color: transparent;
		}
	
</style>
<div class="content-wrapper">
	<section class="content-header">
		<h1>
			Form-Builder
			<small>Generate dynamic form</small>
		</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
			<li class="active">Form-Builder</li>
		</ol>
	</section>
	<section class="content">
	
		<div class="row">
			<div class="col-md-3">
				<input type="text" id="txtFormName" placeholder="Please Enter Your Form Name" class="form-control" style="display:none" /><br />
			</div>
			<div class="col-md-9"></div>
		</div>
		<div id="stage1" class="build-wrap"></div>
		<form class="render-wrap"></form>
		<div class="btn-group pull-right">
			<button type="button" id="edit-form" class="btn btn-secondary edit-form">Edit Form</button>
			<button type="button" id="btnSaveForm" class="btn btn-primary copy-html" style="display:none;" onclick="SaveDynamicForm();">Save Form</button>
		</div>
		@*<div class="action-buttons">
				<h2>Actions</h2>
				<button id="showData" type="button">Show Data</button>
				<button id="clearFields" type="button">Clear All Fields</button>
				<button id="getData" type="button">Get Data</button>
				<button id="getXML" type="button">Get XML Data</button>
				<button id="getJSON" type="button">Get JSON Data</button>
				<button id="getJS" type="button">Get JS Data</button>
				<button id="setData" type="button">Set Data</button>
				<button id="addField" type="button">Add Field</button>
				<button id="removeField" type="button">Remove Field</button>
				<button id="testSubmit" type="submit">Test Submit</button>
				<button id="resetDemo" type="button">Reset Demo</button>
			</div>*@

	</section>
	</div>
<input type="hidden" id="hdnexist" value="False" />
<script src="~/Areas/Admin/Content/formbuilder/js/vendor.js"></script>
<script src="~/Areas/Admin/Content/formbuilder/js/form-builder.min.js"></script>
<script src="~/Areas/Admin/Content/formbuilder/js/form-render.min.js"></script>
<script src="~/Areas/Admin/Content/formbuilder/js/jquery.rateyo.min.js"></script>

<script src="~/Areas/Admin/Content/formbuilder/js/demo.js"></script>

Repo_Pattern_MVC/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Repo_Pattern_MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

Repo_Pattern_MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Repo_Pattern_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	<!-- Latest compiled and minified CSS -->
	<link href="~/Areas/Admin/Content/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />

	<!-- jQuery library -->
	<script src="//code.jquery.com/jquery-1.12.4.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="~/Areas/Admin/Content/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

	<!-- add thids links for the error message-->
	<link href="~/Areas/Admin/Content/toastr.css" rel="stylesheet" />
	<script src="~/Areas/Admin/Content/toastr.js"></script>


	<style>

		.LoadingDiv {
			top: 0;
			left: 0;
			position: fixed;
			opacity: 0.97;
			z-index: 10000000;
			background: Black;
			height: 100%;
			width: 100%;
			margin: auto;
		}

		.red_border {
			border: 1px solid #e46262;
		}
	</style>
</head>
<body>
	<div id="dvLoader" class="LoadingDiv" style="display: none;">
		<table style="height: 100%; margin: auto;">
			<tr>
				<td style="vertical-align: middle;">
					<center>
					
						<img src="~/Content/images/loader.gif" alt="Loading" />
					</center>
				</td>
			</tr>
		</table>
	</div>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Home", "Index", "Home")</li>
					<li>@Html.ActionLink("About", "About", "Home")</li>
					<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>
<script>
	$(document).ready(function () {

		//$('#toast-container').find('.toast-top-center').removeClass('.toast-top-center');
		//toastr.options = {
		//	"closeButton": true,
		//	'autoWidth': false,
		//	"debug": false,
		//	"newestOnTop": true,
		//	"progressBar": true,
		//	"positionClass": "toast-top-center",
		//	"preventDuplicates": false,
		//	"onclick": null,
		//	"showDuration": "300",
		//	"hideDuration": "1000",
		//	"timeOut": "3000",
		//	"extendedTimeOut": "1000",
		//	"showEasing": "swing",
		//	"hideEasing": "linear",
		//	"showMethod": "fadeIn",
		//	"hideMethod": "fadeOut"
		//}
		$('#dvLoader')
			.hide()
			.ajaxStart(function () {
				$(this).show();
			})
			.ajaxStop(function () {
				$(this).hide();
			});
	});
	function CheckRequiredFields() {
		var isValid = true;
		$('.required').each(function () {
			if ($.trim($(this).val()) == '') {
				isValid = false;
				$(this).addClass('red_border');


			}
			else {
				$(this).removeClass('red_border');

			}
		});
		return isValid;
	}
	function checkemail(valemail) {
		var forgetfilter = /^([\w-\.]+)@@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
		if (forgetfilter.test(valemail)) {
			return true;
		}
		else {
			return false;
		}
	}

	function isNumberKey(evt) {
		var charcode = (evt.which) ? evt.which : evt.keycode
		if (charcode > 31 && (charcode < 48 || charcode > 58)
			&& evt.keyCode != 35 && evt.keyCode != 36 && evt.keyCode != 37
			&& evt.keyCode != 38 && evt.keyCode != 39 && evt.keyCode != 40
			&& evt.keyCode != 46) {
			return false;
		}
		else {
			return true;
		}
	}
</script>